### ISSUE TITLE
Update Drupal core to current version

### ISSUE THREAD

**Issue by Markus-Schmitt** [thinktandem/platformsh-example-drupal8#11]
Can you please update the Drupal core version specified to the latest version?  
Cloning the repo and running `lando start` I ended up with Drupal 8.4.4 and was only able to update to 8.4.8 until I ran `lando composer update drupal/core symfony/* --with-dependencies`, which then got me to 8.5.4.  
Thank you

**Comment by labboy0276** [comment]
I took care of this today
